version: "3.9"
services:
    mssql:
        image: 'mcr.microsoft.com/mssql/server'
        container_name: 'ContactDb'
        ports:
            - '1433:1433'
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Neslican26*
        volumes:
            - 'ContactVolume'


            