version: "3.9"

services:
  postgresql:
    image: postgres:latest
    container_name: contactinformationpostgresql
    restart: always
    environment:
      - POSTGRES_USER=abasda
      - POSTGRES_PASSWORD=Neslican26*
    ports:
      - '5555:5432'
    volumes: 
      - 'postgresVolume'
volumes:
  postgresql:
    driver: local


            