version: "3.9"
services:
    mongo-express:
        image: mongo-express
        container_name: mongoexpress
        restart: unless-stopped
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongodb
            - ME_CONFIG_MONGODB_PORT=27017
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
            - ME_CONFIG_MONGODB_AUTH_USERNAME=abasda
            - ME_CONFIG_MONGODB_AUTH_PASSWORD=Neslican2626
            - ME_CONFIG_BASICAUTH_USERNAME=abasda
            - ME_CONFIG_BASICAUTH_PASSWORD=Neslican2626
            - ME_CONFIG_MONGODB_ADMINUSERNAME=abasda
            - ME_CONFIG_MONGODB_ADMINPASSWORD=Neslican2626
        ports:
          - 8081:8081
        volumes: 
            - mongoexpress
        networks:
          - mongonetwork 
        
volumes:
  mongoexpress:
    name: mongoExpressVolume
    driver: local
    external: false
  
networks:
  mongonetwork:
    name: mongonetwork
    driver: bridge    
